Traceback (most recent call last):
  File "/home/josh/Lhydra_rs/data_engineered/rs_main_v2_refactored/train_v2.py", line 309, in <module>
    main()
  File "/home/josh/Lhydra_rs/data_engineered/rs_main_v2_refactored/train_v2.py", line 264, in main
    df = pd.read_csv('data/engineered_data.csv')
  File "/home/josh/anaconda3/envs/ReNeLLM/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/josh/anaconda3/envs/ReNeLLM/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/josh/anaconda3/envs/ReNeLLM/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/josh/anaconda3/envs/ReNeLLM/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/home/josh/anaconda3/envs/ReNeLLM/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/engineered_data.csv'
